# Add 'root' label to any root file changes
# Quotation marks are required for the leading asterisk
Core:
  - changed-files:
      - any-glob-to-any-file: '*'

# Add 'AnyChange' label to any changes within the entire repository
AnyChange:
  - changed-files:
    - any-glob-to-any-file: '**'

# Add 'Documentation' label to any changes within 'docs' folder or any subfolders
Documentation:
  - changed-files:
      - any-glob-to-any-file: ['docs/*', 'guides/*']

Social:
  - changed-files:
      - all-glob-to-all-file: [
        'app/Models/Social/*',
        'app/Http/Controllers/Social/*',
        'app/Http/Requests/Social/*',
        'app/Http/Resources/Social/*',
        'routes/social.php'
      ]

Railway:
  - changed-files:
      - all-glob-to-all-file: [
        'app/Models/Railway/*',
        'app/Http/Controllers/Railway/*',
        'app/Http/Requests/Railway/*',
        'app/Http/Resources/Railway/*',
        'routes/railway.php'
      ]

Support:
  - changed-files:
      - all-glob-to-all-file: [
        'app/Models/Support/*',
        'app/Http/Controllers/Support/*',
        'app/Http/Requests/Support/*',
        'app/Http/Resources/Support/*',
        'routes/support.php'
      ]

Wiki:
  - changed-files:
      - all-glob-to-all-file: [
        'app/Models/Wiki/*',
        'app/Http/Controllers/Wiki/*',
        'app/Http/Requests/Wiki/*',
        'app/Http/Resources/Wiki/*',
        'routes/wiki.php'
      ]

Config:
  - changed-files:
      - all-glob-to-all-file: [
        'app/Models/Config/*',
        'app/Http/Controllers/Config/*',
        'app/Http/Requests/Config/*',
        'app/Http/Resources/Config/*',
        'routes/support.php'
      ]

User:
  - changed-files:
      - all-glob-to-all-file: [
        'app/Models/User/*',
        'app/Http/Controllers/User/*',
        'app/Http/Requests/User/*',
        'app/Http/Resources/User/*',
        'routes/user.php'
      ]



