blank_issues_enabled: false
contact_links:
  - name: Vous avez une question
    url: https://github.com/vortechstudio-packager/laravel-github-issues/discussions/categories/q-a
    about: Demander à notre communauté

  - name: J'ai une idée pour ce package ?
    url: https://github.com/vortechstudio-packager/laravel-github-issues/discussions/categories/ideas
    about: Proposer une idée pour ce package

  - name: J'ai trouvé une faille de sécurité
    url: https://github.com/Vortech Studio/laravel-github-issues/security/policy
    about: Découvrez comment nous signaler les bugs sensibles
