name: CodeStyle

on:
  push:
    paths:
      - '**.php'
    branches:
      - develop

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.3.1

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling
          branch: dev-fix-codestyle
          create_branch: true
