name: Notify Update Project
on:
  project_card:
    types: ["moved"]


jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Envoie d'un message à un groupe Télégramme
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} à changer un status pour le projet vortechstudio:

            - ${{ github.event.payload.project_card }}
